#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from mt5_portfolio_live_profile import create_profile, load_yaml, safe_name
from mt5_compile_win import compile_portfolio_sources, sync_mql5_files


MT5_HOME = Path(os.environ.get("MT5_HOME", r"C:\Program Files\MetaTrader 5"))
MT5_TERMINAL = MT5_HOME / "terminal64.exe"
MT5_DATA = Path(
    os.environ.get(
        "MT5_DATA",
        os.path.expandvars(r"%APPDATA%\MetaQuotes\Terminal\D0E8209F77C8CF37AD8BF550E51FF075"),
    )
)
DEFAULT_PROFILE_ROOT = ROOT / "temp" / "portfolio_profiles"


@dataclass(frozen=True)
class StartupAssets:
    templates: list[Path]
    setup_set: Path
    config_ini: Path


def install_profile(generated_profile: Path, mt5_data: Path, profile_name: str) -> Path:
    target = mt5_data / "MQL5" / "Profiles" / "Charts" / profile_name
    if target.exists():
        shutil.rmtree(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(generated_profile, target)
    return target


def start_terminal(mt5_home: Path, profile_name: str) -> None:
    terminal = mt5_home / "terminal64.exe"
    if not terminal.exists():
        raise SystemExit(f"missing terminal: {terminal}")
    subprocess.Popen([str(terminal), f"/profile:{profile_name}"], cwd=str(mt5_home))


def start_with_config(mt5_home: Path, config_ini: Path) -> None:
    terminal = mt5_home / "terminal64.exe"
    if not terminal.exists():
        raise SystemExit(f"missing terminal: {terminal}")
    subprocess.Popen([str(terminal), f"/config:{config_ini}"], cwd=str(mt5_home))


def read_utf16(path: Path) -> str:
    return path.read_text(encoding="utf-16-le", errors="replace")


def write_utf16(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-16-le")


def write_utf8(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def render_startup_ini(
    account: dict,
    symbol: str,
    period_size: int,
    setup_set_name: str,
) -> str:
    common_lines = ["[Common]"]
    if account.get("login"):
        common_lines.append(f"Login={account['login']}")
    if account.get("server"):
        common_lines.append(f"Server={account['server']}")
    if account.get("proxy_enable") is not None:
        common_lines.append(f"ProxyEnable={account['proxy_enable']}")
    if account.get("proxy_type") is not None:
        common_lines.append(f"ProxyType={account['proxy_type']}")
    if account.get("proxy_address"):
        common_lines.append(f"ProxyAddress={account['proxy_address']}")

    lines = [
        "; WaiTrade2 portfolio startup generated by mt5_portfolio_deploy_win.py",
        *common_lines,
        "",
        "[Experts]",
        "Enabled=1",
        "AllowLiveTrading=1",
        "AllowDllImport=0",
        "",
        "[StartUp]",
        r"Expert=WaiTrade2\PortfolioSetup",
        f"ExpertParameters={setup_set_name}",
        f"Symbol={symbol}",
        f"Period=M{period_size}",
        "",
    ]
    return "\n".join(lines)


def install_startup_assets(
    generated_profile: Path,
    mt5_data: Path,
    profile_name: str,
    strategy_config: Path,
    setup_delay_sec: int = 5,
) -> StartupAssets:
    manifest_path = generated_profile / "portfolio_manifest.yaml"
    if not manifest_path.exists():
        raise SystemExit(f"missing manifest: {manifest_path}")

    import yaml

    manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8")) or {}
    charts = manifest.get("charts") or []
    if not charts:
        raise SystemExit(f"manifest has no charts: {manifest_path}")
    symbol = str(charts[0].get("symbol") or "")
    if not symbol:
        raise SystemExit(f"manifest chart has no symbol: {manifest_path}")

    safe_profile = safe_name(profile_name or str(manifest.get("schedule") or "portfolio"))
    templates_dir = mt5_data / "MQL5" / "Profiles" / "Templates"
    presets_dir = mt5_data / "MQL5" / "Presets"
    startup_dir = ROOT / "temp" / "portfolio_startup"
    template_names: list[str] = []
    template_paths: list[Path] = []
    period_sizes: list[str] = []

    for index, chart in enumerate(charts, 1):
        chart_name = str(chart.get("chart") or f"chart{index:02d}.chr")
        source = generated_profile / chart_name
        if not source.exists():
            raise SystemExit(f"missing generated chart for startup template: {source}")
        template_name = f"{safe_profile}_{Path(chart_name).stem}.tpl"
        target = templates_dir / template_name
        write_utf16(target, read_utf16(source))
        template_names.append(template_name)
        template_paths.append(target)
        period_sizes.append(str(int(chart.get("period_size") or 5)))

    setup_set_name = f"{safe_profile}_setup.set"
    setup_set = presets_dir / setup_set_name
    write_utf8(
        setup_set,
        "\n".join(
            [
                f"InpSymbol={symbol}",
                f"InpPeriodsCsv={','.join(period_sizes)}",
                f"InpTemplatesCsv={','.join(template_names)}",
                f"InpSetupDelaySec={setup_delay_sec}",
                "",
            ]
        ),
    )

    account = load_yaml(strategy_config).get("mt5_account") or {}
    config_ini = startup_dir / f"{safe_profile}_startup.ini"
    write_utf8(
        config_ini,
        render_startup_ini(
            account,
            symbol=symbol,
            period_size=int(period_sizes[0]),
            setup_set_name=setup_set_name,
        ),
    )
    return StartupAssets(templates=template_paths, setup_set=setup_set, config_ini=config_ini)


def deploy(args: argparse.Namespace) -> tuple[Path, Path]:
    profile_name = args.profile_name or safe_name(args.schedule)
    generated = create_profile(
        args.schedule,
        args.schedule_config,
        args.strategy_config,
        args.generated_root,
        args.guard_key_suffix,
        getattr(args, "no_entry_month", None),
    )
    sync_mql5_files(args.mt5_data)
    installed = install_profile(generated, args.mt5_data, profile_name)
    if args.compile:
        results = compile_portfolio_sources(args.mt5_home, args.mt5_data)
        failed = [result for result in results if not result.success]
        if failed:
            for result in failed:
                print(f"compile failed: {result.source} ({result.message}) log={result.log}")
            raise SystemExit(1)
    if args.start:
        start_mode = getattr(args, "start_mode", "profile")
        if start_mode == "startup":
            assets = install_startup_assets(
                generated,
                args.mt5_data,
                profile_name,
                args.strategy_config,
                getattr(args, "setup_delay_sec", 5),
            )
            start_with_config(args.mt5_home, assets.config_ini)
        else:
            start_terminal(args.mt5_home, profile_name)
    return generated, installed


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Deploy a portfolio schedule profile into Windows MT5 without starting by default."
    )
    parser.add_argument("--schedule", default="r186_r196_season_guard")
    parser.add_argument("--schedule-config", type=Path, default=ROOT / "config" / "portfolio_schedules.yaml")
    parser.add_argument("--strategy-config", type=Path, default=ROOT / "config" / "strategies.yaml")
    parser.add_argument("--generated-root", type=Path, default=DEFAULT_PROFILE_ROOT)
    parser.add_argument("--profile-name", default="")
    parser.add_argument("--guard-key-suffix", default="")
    parser.add_argument(
        "--no-entry-month",
        type=int,
        help="Override all streams with InpEntryMonths=N before installing. Use with a debug suffix for load-only guard audits.",
    )
    parser.add_argument("--mt5-home", type=Path, default=MT5_HOME)
    parser.add_argument("--mt5-data", type=Path, default=MT5_DATA)
    parser.add_argument("--compile", action="store_true")
    parser.add_argument("--start", action="store_true", help="Start MT5 after deploying. Default is deploy only.")
    parser.add_argument(
        "--start-mode",
        choices=("profile", "startup"),
        default="profile",
        help="profile uses /profile; startup uses /config:[StartUp] PortfolioSetup + templates.",
    )
    parser.add_argument("--setup-delay-sec", type=int, default=5)
    args = parser.parse_args()

    generated, installed = deploy(args)
    print(f"generated_profile={generated}")
    print(f"installed_profile={installed}")
    print(f"start_command={args.mt5_home / 'terminal64.exe'} /profile:{installed.name}")
    if args.start_mode == "startup":
        assets = install_startup_assets(
            generated,
            args.mt5_data,
            installed.name,
            args.strategy_config,
            args.setup_delay_sec,
        )
        print(f"startup_config={assets.config_ini}")
        print(f"startup_set={assets.setup_set}")
        print(f"startup_templates={len(assets.templates)}")
    if not args.start:
        print("not_started=true")


if __name__ == "__main__":
    main()
