#!/usr/bin/env python3
"""YAML策略定义 → MT5 .set 文件转换器"""

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("错误: 需要 PyYAML，请执行 pip install pyyaml", file=sys.stderr)
    sys.exit(1)

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_YAML = SCRIPT_DIR.parent / "config" / "strategies.yaml"

NON_STRATEGY_KEYS = {'defaults', 'symbols', 'backtest_defaults', 'mt5_account'}

# YAML key → .set INP 名称映射
FLAT_MAP = {
    "bounce_pct": "InpBouncePct",
    "timeout_min": "InpTimeoutMin",
    "max_entry_offset_r": "InpMaxEntryOffsetR",
    "entry_depth_pct": "InpEntryDepthPct",
    "entry_depth_filter": "InpEntryDepthFilter",
    "entry_depth_relax_min_balance": "InpEntryDepthRelaxMinBalance",
    "deep_entry_boost": "InpDeepEntryBoost",
    "entry_confirm_bars": "InpEntryConfirmBars",
    "bounce_close_confirm_bars": "InpBounceCloseConfirmBars",
    "bounce_close_tf": "InpBounceCloseTF",
    "bounce_close_buffer_pct": "InpBounceCloseBufferPct",
    "bounce_close_require_body": "InpBounceCloseRequireBody",
    "bounce_close_min_body_pct": "InpBounceCloseMinBodyPct",
    "bounce_close_weak_body_pct": "InpBounceCloseWeakBodyPct",
    "bounce_close_weak_body_mult": "InpBounceCloseWeakBodyMult",
    "defensive_confirm_max_balance": "InpDefensiveConfirmMaxBalance",
    "defensive_confirm_min_price": "InpDefensiveConfirmMinPrice",
    "defensive_confirm_max_price": "InpDefensiveConfirmMaxPrice",
    "defensive_bounce_close_confirm_bars": "InpDefensiveBounceCloseConfirmBars",
    "defensive_bounce_close_buffer_pct": "InpDefensiveBounceCloseBufferPct",
    "defensive_bounce_close_require_body": "InpDefensiveBounceCloseRequireBody",
    "defensive_bounce_close_min_body_pct": "InpDefensiveBounceCloseMinBodyPct",
    "defensive_bounce_close_weak_body_pct": "InpDefensiveBounceCloseWeakBodyPct",
    "defensive_bounce_close_weak_body_mult": "InpDefensiveBounceCloseWeakBodyMult",
    "defensive_bounce_sweet_min_pct": "InpDefensiveBounceSweetMinPct",
    "defensive_bounce_sweet_max_pct": "InpDefensiveBounceSweetMaxPct",
    "defensive_outside_bounce_sweet_mult": "InpDefensiveOutsideBounceSweetMult",
    "defensive_max_entries_per_ob": "InpDefensiveMaxEntriesPerOB",
    "defensive_ob_reentry_cooldown_min": "InpDefensiveOBReentryCooldownMin",
    "defensive_shallow_confirm_pos_min": "InpDefensiveShallowConfirmPosMin",
    "defensive_shallow_confirm_pos_mult": "InpDefensiveShallowConfirmPosMult",
    "runtime_defensive_drawdown_pct": "InpRuntimeDefensiveDrawdownPct",
    "runtime_defensive_min_trades": "InpRuntimeDefensiveMinTrades",
    "runtime_defensive_max_balance": "InpRuntimeDefensiveMaxBalance",
    "runtime_defensive_pos_mult": "InpRuntimeDefensivePosMult",
    # 自适应噪音门控
    "adaptive_noise_drawdown_pct": "InpAdaptiveNoiseDrawdownPct",
    "adaptive_noise_def_min_dir_ratio": "InpAdaptiveNoiseDefMinDirRatio",
    "adaptive_noise_def_max_range_atr": "InpAdaptiveNoiseDefMaxRangeATR",
    "adaptive_noise_recovery_pct": "InpAdaptiveNoiseRecoveryPct",
    "adaptive_noise_def_boost_mult": "InpAdaptiveNoiseDefBoostMult",
    "adaptive_noise_def_cooldown_bars": "InpAdaptiveNoiseDefCooldownBars",
    # Mitigation Entry (SMC P0改进: 震荡市替代Bounce Entry)
    "enable_mitigation_entry": "InpEnableMitigationEntry",
    "mitigation_entry_max_bars": "InpMitigationEntryMaxBars",
    "mitigation_entry_only_range": "InpMitigationEntryOnlyRange",
    "mitigation_entry_only_defensive": "InpMitigationEntryOnlyDefensive",
    "mitigation_entry_signal_types": "InpMitigationEntrySignalTypes",
    # 双扫确认 (SMC路径B)
    "enable_double_sweep_confirm": "InpEnableDoubleSweepConfirm",
    "double_sweep_window_bars": "InpDoubleSweepWindowBars",
    "double_sweep_only_defensive": "InpDoubleSweepOnlyDefensive",
    "double_sweep_block_sweep_entry": "InpDoubleSweepBlockSweepEntry",
    "double_sweep_dtp_trigger_r": "InpDoubleSweepDTPTriggerR",
    "double_sweep_regime_pos_mult": "InpDoubleSweepRegimePosMult",
    # FVG (公允价值缺口)
    "enable_fvg": "InpEnableFVG",
    "fvg_lookback_bars": "InpFVGLookbackBars",
    "fvg_min_gap_atr": "InpFVGMinGapATR",
    "fvg_max_gap_atr": "InpFVGMaxGapATR",
    "fvg_max_age_bars": "InpFVGMaxAgeBars",
    "fvg_timeout_min": "InpFVGTimeoutMin",
    "fvg_require_range_boundary": "InpFVGRequireRangeBoundary",
    "fvg_enable_fade_entry": "InpFVGEnableFadeEntry",
    "fvg_fade_min_risk_spread_ratio": "InpFVGFadeMinRiskSpreadRatio",
    "fvg_fade_max_entry_offset_r": "InpFVGFadeMaxEntryOffsetR",
    "fvg_fade_pos_mult": "InpFVGFadePosMult",
    "fvg_fade_max_lot_size": "InpFVGFadeMaxLotSize",
    "fvg_fade_tp_mult": "InpFVGFadeTPMult",
    "fvg_no_entry_hours": "InpFVGNoEntryHours",
    "fvg_require_confirm_candle": "InpFVGRequireConfirmCandle",
    "fvg_require_h1_aligned": "InpFVGRequireH1Aligned",
    # ATR体制检测
    "atr_regime_period": "InpATRRegimePeriod",
    "atr_regime_low_threshold": "InpATRRegimeLowThreshold",
    "atr_regime_low_max_pos_mult": "InpATRRegimeLowMaxPosMult",
    "atr_regime_low_dtp_trigger_r": "InpATRRegimeLowDTPTriggerR",
    "enable_confirm_pullback": "InpEnableConfirmPullback",
    "confirm_pullback_pct": "InpConfirmPullbackPct",
    "confirm_pullback_wait_sec": "InpConfirmPullbackWaitSec",
    "confirm_pullback_max_adverse_pct": "InpConfirmPullbackMaxAdversePct",
    "enable_entry_momentum_filter": "InpEnableEntryMomentumFilter",
    "entry_momentum_tf": "InpEntryMomentumTF",
    "entry_block_counter_strong": "InpEntryBlockCounterStrong",
    "entry_require_counter_weak": "InpEntryRequireCounterWeak",
    "require_double_touch": "InpRequireDoubleTch",
    "double_touch_window_min": "InpDoubleTchWindowMin",
    "min_ob_spread_mult": "InpMinOBSpreadMult",
    "min_risk_spread_ratio": "InpMinRiskSpreadRatio",
    "min_abs_risk_usd": "InpMinAbsRiskUSD",
    "min_ob_body_pct": "InpMinOBBodyPct",
    "min_impulse_body_pct": "InpMinImpulseBodyPct",
    "min_impulse_vol_ratio": "InpMinImpulseVolRatio",
    "structure_break_bars": "InpStructureBreakBars",
    "structure_break_atr": "InpStructureBreakATR",
    "require_impulse_candle_dir": "InpRequireImpulseCandleDir",
    "enable_range_breakout": "InpEnableRangeBreakout",
    "range_breakout_only": "InpRangeBreakoutOnly",
    "range_breakout_bars": "InpRangeBreakoutBars",
    "range_breakout_max_atr": "InpRangeBreakoutMaxATR",
    "range_breakout_min_spread_mult": "InpRangeBreakoutMinSpreadMult",
    "range_breakout_atr": "InpRangeBreakoutATR",
    "range_breakout_tp_mult": "InpRangeBreakoutTPMult",
    "range_breakout_body_dir": "InpRangeBreakoutBodyDir",
    "enable_htf_pullback": "InpEnableHTFPullback",
    "htf_pullback_only": "InpHTFPullbackOnly",
    "htf_pullback_tf": "InpHTFPullbackTF",
    "htf_pullback_bars": "InpHTFPullbackBars",
    "htf_pullback_min_atr": "InpHTFPullbackMinATR",
    "htf_pullback_zone_atr": "InpHTFPullbackZoneATR",
    "htf_pullback_offset_atr": "InpHTFPullbackOffsetATR",
    "htf_pullback_tp_mult": "InpHTFPullbackTPMult",
    # HTF Range Fade: 大周期震荡区间高抛低吸
    "enable_range_fade": "InpEnableRangeFade",
    "range_tf": "InpRangeTF",
    "range_lookback": "InpRangeLookback",
    "range_min_bars": "InpRangeMinBars",
    "range_min_width_atr": "InpRangeMinWidthATR",
    "range_max_width_atr": "InpRangeMaxWidthATR",
    "range_boundary_tolerance_atr": "InpRangeBoundaryToleranceATR",
    "range_swing_strength": "InpRangeSwingStrength",
    "range_min_touches": "InpRangeMinTouches",
    "range_min_containment": "InpRangeMinContainment",
    "range_entry_zone_atr": "InpRangeEntryZoneATR",
    "range_sl_buffer_atr": "InpRangeSLBufferATR",
    "range_tp_target": "InpRangeTPTarget",
    "range_pos_mult": "InpRangePosMult",
    "range_max_lot": "InpRangeMaxLot",
    "range_update_bars": "InpRangeUpdateBars",
    "range_require_sweep": "InpRangeRequireSweep",
    "range_require_fvg": "InpRangeRequireFVG",
    "range_no_mid_trades": "InpRangeNoMidTrades",
    "enable_liquidity_sweep": "InpEnableLiquiditySweep",
    "liquidity_sweep_only": "InpLiquiditySweepOnly",
    "sweep_lookback_bars": "InpSweepLookbackBars",
    "sweep_max_range_atr": "InpSweepMaxRangeATR",
    "sweep_min_range_spread_mult": "InpSweepMinRangeSpreadMult",
    "sweep_min_penetration_atr": "InpSweepMinPenetrationATR",
    "sweep_min_wick_pct": "InpSweepMinWickPct",
    "sweep_tp_mult": "InpSweepTPMult",
    "enable_loose_sweep": "InpEnableLooseSweep",
    "loose_sweep_lookback_bars": "InpLooseSweepLookbackBars",
    "loose_sweep_max_range_atr": "InpLooseSweepMaxRangeATR",
    "loose_sweep_min_range_spread_mult": "InpLooseSweepMinRangeSpreadMult",
    "loose_sweep_min_penetration_atr": "InpLooseSweepMinPenetrationATR",
    "loose_sweep_min_wick_pct": "InpLooseSweepMinWickPct",
    "no_ob_start_hour": "InpNoOBStartHour",
    "no_ob_end_hour": "InpNoOBEndHour",
    "min_ob_strength": "InpMinOBStrength",
    "max_risk_atr": "InpMaxRiskATR",
    "max_counter_risk_atr": "InpMaxCounterRiskATR",
    "consolidate_ob": "InpConsolidateOB",
    "sl_buffer_atr": "InpSLBufferATR",
    "virtual_sl_confirm_bars": "InpVirtualSLConfirmBars",
    "virtual_sl_confirm_tf": "InpVirtualSLConfirmTF",
    "virtual_sl_hard_buffer_r": "InpVirtualSLHardBufferR",
    "virtual_sl_close_buffer_atr": "InpVirtualSLCloseBufferATR",
    "virtual_sl_breach_sec": "InpVirtualSLBreachSec",
    "defensive_virtual_sl_confirm_bars": "InpDefensiveVirtualSLConfirmBars",
    "defensive_virtual_sl_hard_buffer_r": "InpDefensiveVirtualSLHardBufferR",
    "defensive_virtual_sl_close_buffer_atr": "InpDefensiveVirtualSLCloseBufferATR",
    "impulse_atr_mult": "InpImpulseATRMult",
    "impulse_lookback": "InpImpulseLookback",
    "atr_period": "InpATRPeriod",
    "breakeven_r": "InpBreakevenR",
    "breakeven_lock_r": "InpBreakevenLockR",
    "breakeven_stage2_r": "InpBreakevenStage2R",
    "breakeven_stage2_lock_r": "InpBreakevenStage2LockR",
    "early_loss_cut_r": "InpEarlyLossCutR",
    "mfe_fail_min_r": "InpMFEFailMinR",
    "mfe_fail_exit_r": "InpMFEFailExitR",
    "no_mfe_exit_bars": "InpNoMFEExitBars",
    "no_mfe_min_peak_r": "InpNoMFEMinPeakR",
    "no_mfe_exit_r": "InpNoMFEExitR",
    "enable_failure_reverse": "InpEnableFailureReverse",
    "reverse_on_early_loss": "InpReverseOnEarlyLoss",
    "reverse_on_mfe_fail": "InpReverseOnMFEFail",
    "reverse_on_no_mfe": "InpReverseOnNoMFE",
    "failure_reverse_risk_mult": "InpFailureReverseRiskMult",
    "failure_reverse_lot_mult": "InpFailureReverseLotMult",
    "failure_reverse_tp_r": "InpFailureReverseTPR",
    "failure_reverse_allow_chain": "InpFailureReverseAllowChain",
    "dtp_trigger_r": "InpDTPTriggerR",
    "dtp_retrace": "InpDTPRetrace",
    "adaptive_dtp": "InpAdaptiveDTP",
    "dtp_stage2_trigger_r": "InpDTPStage2TriggerR",
    "dtp_stage2_retrace": "InpDTPStage2Retrace",
    "dtp_stage3_trigger_r": "InpDTPStage3TriggerR",
    "dtp_stage3_retrace": "InpDTPStage3Retrace",
    "dtp_exit_mode": "InpDTPExitMode",
    "dtp_partial_pct": "InpDTPPartialPct",
    "dtp_post_partial_retrace": "InpDTPPostPartialRetrace",
    "dtp_post_partial_lock_r": "InpDTPPostPartialLockR",
    "dtp_reset_peak_after_partial": "InpDTPResetPeakAfterPartial",
    "time_exit_bars": "InpTimeExitBars",
    "time_decay_tp": "InpTimeDecayTP",
    "risk_percent": "InpRiskPercent",
    "fixed_lot_size": "InpFixedLotSize",
    "enable_pos_mult": "InpEnablePosMult",
    "max_pos_mult": "InpMaxPosMult",
    "max_lot_size": "InpMaxLotSize",
    "sweep_pos_mult": "InpSweepPosMult",
    "range_breakout_pos_mult": "InpRangeBreakoutPosMult",
    "htf_pullback_pos_mult": "InpHTFPullbackPosMult",
    "sweep_max_lot_size": "InpSweepMaxLotSize",
    "loose_sweep_pos_mult": "InpLooseSweepPosMult",
    "loose_sweep_max_lot_size": "InpLooseSweepMaxLotSize",
    "loose_sweep_max_active_zones": "InpLooseSweepMaxActiveZones",
    "range_breakout_max_lot_size": "InpRangeBreakoutMaxLotSize",
    "htf_pullback_max_lot_size": "InpHTFPullbackMaxLotSize",
    "htf_pullback_allow_hours": "InpHTFPullbackAllowHours",
    "htf_pullback_no_hours": "InpHTFPullbackNoHours",
    "htf_pullback_risk_min": "InpHTFPullbackRiskMin",
    "htf_pullback_risk_max": "InpHTFPullbackRiskMax",
    "htf_pullback_confirm_min": "InpHTFPullbackConfirmMin",
    "htf_pullback_confirm_max": "InpHTFPullbackConfirmMax",
    "htf_pullback_context_mult": "InpHTFPullbackContextMult",
    "sweep_allow_hours": "InpSweepAllowHours",
    "sweep_no_hours": "InpSweepNoHours",
    "sweep_context_months": "InpSweepContextMonths",
    "sweep_context_max_day": "InpSweepContextMaxDay",
    "sweep_context_min_month_start_balance": "InpSweepContextMinMonthStartBalance",
    "sweep_context_no_hours": "InpSweepContextNoHours",
    "sweep_bad_risk_min": "InpSweepBadRiskMin",
    "sweep_bad_risk_max": "InpSweepBadRiskMax",
    "sweep_bad_risk_mult": "InpSweepBadRiskMult",
    "sweep_min_balance": "InpSweepMinBalance",
    "sweep_low_balance_threshold": "InpSweepLowBalanceThreshold",
    "sweep_low_balance_mult": "InpSweepLowBalanceMult",
    "sweep_monthly_negative_mult": "InpSweepMonthlyNegativeMult",
    "sweep_monthly_profit_start_pct": "InpSweepMonthlyProfitStartPct",
    "sweep_early_bounce_sec_min": "InpSweepEarlyBounceSecMin",
    "sweep_early_bounce_sec_max": "InpSweepEarlyBounceSecMax",
    "sweep_early_bounce_mult": "InpSweepEarlyBounceMult",
    "sweep_early_bounce_hours": "InpSweepEarlyBounceHours",
    "sweep_bad_age_min_bars": "InpSweepBadAgeMinBars",
    "sweep_bad_age_max_bars": "InpSweepBadAgeMaxBars",
    "sweep_bad_age_mult": "InpSweepBadAgeMult",
    "ob_pos_mult": "InpOBPosMult",
    "ob_pos_mult_min_balance": "InpOBPosMultMinBalance",
    "ob_bad_hours": "InpOBBadHours",
    "ob_bad_hour_mult": "InpOBBadHourMult",
    "low_balance_ob_bad_hours": "InpLowBalanceOBBadHours",
    "low_balance_ob_bad_months": "InpLowBalanceOBBadMonths",
    "low_balance_ob_bad_max_month_start_balance": "InpLowBalanceOBBadMaxMonthStartBalance",
    "low_balance_ob_bad_hour_mult": "InpLowBalanceOBBadHourMult",
    "low_balance_threshold": "InpLowBalanceThreshold",
    "low_balance_pos_mult": "InpLowBalancePosMult",
    "low_balance_max_lot_size": "InpLowBalanceMaxLotSize",
    "monthly_guard_min_balance": "InpMonthlyGuardMinBalance",
    "monthly_loss_stop_pct": "InpMonthlyLossStopPct",
    "monthly_loss_stop_min_trades": "InpMonthlyLossStopMinTrades",
    "monthly_early_loss_stop_trades": "InpMonthlyEarlyLossStopTrades",
    "monthly_early_loss_stop_pct": "InpMonthlyEarlyLossStopPct",
    "monthly_early_loss_stop_min_balance": "InpMonthlyEarlyLossStopMinBalance",
    "monthly_early_loss_stop_continuous": "InpMonthlyEarlyLossStopContinuous",
    "monthly_negative_pos_mult": "InpMonthlyNegativePosMult",
    "monthly_warmup_profit_pct": "InpMonthlyWarmupProfitPct",
    "monthly_warmup_pos_mult": "InpMonthlyWarmupPosMult",
    "monthly_defensive_loss_pct": "InpMonthlyDefensiveLossPct",
    "monthly_defensive_until_profit_pct": "InpMonthlyDefensiveUntilProfitPct",
    "monthly_defensive_max_month_start_balance": "InpMonthlyDefensiveMaxMonthStartBalance",
    "monthly_defensive_min_trades": "InpMonthlyDefensiveMinTrades",
    "monthly_defensive_no_entry_hours": "InpMonthlyDefensiveNoEntryHours",
    "monthly_defensive_no_buy_hours": "InpMonthlyDefensiveNoBuyHours",
    "monthly_defensive_no_sell_hours": "InpMonthlyDefensiveNoSellHours",
    "monthly_defensive_pos_mult": "InpMonthlyDefensivePosMult",
    "monthly_profit_lock_min_balance": "InpMonthlyProfitLockMinBalance",
    "monthly_profit_lock_start_pct": "InpMonthlyProfitLockStartPct",
    "monthly_profit_lock_keep_pct": "InpMonthlyProfitLockKeepPct",
    "monthly_profit_target_stop_pct": "InpMonthlyProfitTargetStopPct",
    "monthly_profit_target_stop_min_balance": "InpMonthlyProfitTargetStopMinBalance",
    "monthly_profit_target_stop_max_balance": "InpMonthlyProfitTargetStopMaxBalance",
    "monthly_profit_target_stop_months": "InpMonthlyProfitTargetStopMonths",
    "monthly_profit_target_stop2_pct": "InpMonthlyProfitTargetStop2Pct",
    "monthly_profit_target_stop2_min_balance": "InpMonthlyProfitTargetStop2MinBalance",
    "monthly_profit_target_stop2_max_balance": "InpMonthlyProfitTargetStop2MaxBalance",
    "monthly_profit_target_stop2_months": "InpMonthlyProfitTargetStop2Months",
    "shared_monthly_guard": "InpSharedMonthlyGuard",
    "shared_monthly_guard_key": "InpSharedMonthlyGuardKey",
    "shared_monthly_guard_debug": "InpSharedMonthlyGuardDebug",
    "max_concurrent": "InpMaxConcurrent",
    "free_run_min_r": "InpFreeRunMinR",
    "cooldown_bars": "InpCooldownBars",
    "entry_months": "InpEntryMonths",
    "high_balance_no_entry_months": "InpHighBalanceNoEntryMonths",
    "high_balance_no_entry_min_month_start_balance": "InpHighBalanceNoEntryMinMonthStartBalance",
    "no_entry_hours": "InpNoEntryHours",
    "no_buy_hours": "InpNoBuyHours",
    "no_sell_hours": "InpNoSellHours",
    "low_risk_hours": "InpLowRiskHours",
    "low_risk_hour_mult": "InpLowRiskHourMult",
    "high_risk_hours": "InpHighRiskHours",
    "high_risk_hour_mult": "InpHighRiskHourMult",
    "context_filter1_months": "InpContextFilter1Months",
    "context_filter1_no_hours": "InpContextFilter1NoHours",
    "context_filter1_no_buy_hours": "InpContextFilter1NoBuyHours",
    "context_filter1_no_sell_hours": "InpContextFilter1NoSellHours",
    "context_filter1_min_month_start_balance": "InpContextFilter1MinMonthStartBalance",
    "context_filter1_max_month_start_balance": "InpContextFilter1MaxMonthStartBalance",
    "context_filter1_max_balance": "InpContextFilter1MaxBalance",
    "context_filter1_min_price": "InpContextFilter1MinPrice",
    "context_filter1_max_price": "InpContextFilter1MaxPrice",
    "context_filter1_mult": "InpContextFilter1Mult",
    "context_filter2_months": "InpContextFilter2Months",
    "context_filter2_no_hours": "InpContextFilter2NoHours",
    "context_filter2_no_buy_hours": "InpContextFilter2NoBuyHours",
    "context_filter2_no_sell_hours": "InpContextFilter2NoSellHours",
    "context_filter2_min_month_start_balance": "InpContextFilter2MinMonthStartBalance",
    "context_filter2_max_month_start_balance": "InpContextFilter2MaxMonthStartBalance",
    "context_filter2_max_balance": "InpContextFilter2MaxBalance",
    "context_filter2_min_price": "InpContextFilter2MinPrice",
    "context_filter2_max_price": "InpContextFilter2MaxPrice",
    "context_filter2_mult": "InpContextFilter2Mult",
    "context_filter3_months": "InpContextFilter3Months",
    "context_filter3_no_hours": "InpContextFilter3NoHours",
    "context_filter3_no_buy_hours": "InpContextFilter3NoBuyHours",
    "context_filter3_no_sell_hours": "InpContextFilter3NoSellHours",
    "context_filter3_min_month_start_balance": "InpContextFilter3MinMonthStartBalance",
    "context_filter3_max_month_start_balance": "InpContextFilter3MaxMonthStartBalance",
    "context_filter3_max_balance": "InpContextFilter3MaxBalance",
    "context_filter3_min_price": "InpContextFilter3MinPrice",
    "context_filter3_max_price": "InpContextFilter3MaxPrice",
    "context_filter3_mult": "InpContextFilter3Mult",
    "context_filter4_months": "InpContextFilter4Months",
    "context_filter4_no_hours": "InpContextFilter4NoHours",
    "context_filter4_no_buy_hours": "InpContextFilter4NoBuyHours",
    "context_filter4_no_sell_hours": "InpContextFilter4NoSellHours",
    "context_filter4_min_month_start_balance": "InpContextFilter4MinMonthStartBalance",
    "context_filter4_max_month_start_balance": "InpContextFilter4MaxMonthStartBalance",
    "context_filter4_max_balance": "InpContextFilter4MaxBalance",
    "context_filter4_min_price": "InpContextFilter4MinPrice",
    "context_filter4_max_price": "InpContextFilter4MaxPrice",
    "context_filter4_mult": "InpContextFilter4Mult",
    "context_filter5_months": "InpContextFilter5Months",
    "context_filter5_no_hours": "InpContextFilter5NoHours",
    "context_filter5_no_buy_hours": "InpContextFilter5NoBuyHours",
    "context_filter5_no_sell_hours": "InpContextFilter5NoSellHours",
    "context_filter5_min_month_start_balance": "InpContextFilter5MinMonthStartBalance",
    "context_filter5_max_month_start_balance": "InpContextFilter5MaxMonthStartBalance",
    "context_filter5_max_balance": "InpContextFilter5MaxBalance",
    "context_filter5_min_price": "InpContextFilter5MinPrice",
    "context_filter5_max_price": "InpContextFilter5MaxPrice",
    "context_filter5_mult": "InpContextFilter5Mult",
    "context_reverse_hours": "InpContextReverseHours",
    "context_reverse_directions": "InpContextReverseDirections",
    "context_reverse_sell_early_day_max": "InpContextReverseSellEarlyDayMax",
    "context_reverse_sell_late_day_min": "InpContextReverseSellLateDayMin",
    "context_reverse_min_price": "InpContextReverseMinPrice",
    "context_reverse_max_price": "InpContextReverseMaxPrice",
    "context_reverse_max_month_start_balance": "InpContextReverseMaxMonthStartBalance",
    "context_reverse_risk_mult": "InpContextReverseRiskMult",
    "context_reverse_max_risk": "InpContextReverseMaxRisk",
    "context_reverse_tp_r": "InpContextReverseTPR",
    "context_be_min_price": "InpContextBEMinPrice",
    "context_be_max_price": "InpContextBEMaxPrice",
    "context_be_max_month_start_balance": "InpContextBEMaxMonthStartBalance",
    "context_be_r": "InpContextBER",
    "context_be_lock_r": "InpContextBELockR",
    "late_bounce_sec": "InpLateBounceSec",
    "late_bounce_mult": "InpLateBounceMult",
    "bounce_sweet_min_pct": "InpBounceSweetMinPct",
    "bounce_sweet_max_pct": "InpBounceSweetMaxPct",
    "outside_bounce_sweet_mult": "InpOutsideBounceSweetMult",
    "bad_risk_min": "InpBadRiskMin",
    "bad_risk_max": "InpBadRiskMax",
    "bad_risk_mult": "InpBadRiskMult",
    "large_risk_min": "InpLargeRiskMin",
    "large_risk_mult": "InpLargeRiskMult",
    "shallow_confirm_pos_min": "InpShallowConfirmPosMin",
    "shallow_confirm_pos_mult": "InpShallowConfirmPosMult",
    "bad_cluster_min_balance": "InpBadClusterMinBalance",
    "bad_cluster_only_monthly_negative": "InpBadClusterOnlyMonthlyNegative",
    "bad_cluster1_hours": "InpBadCluster1Hours",
    "bad_cluster1_risk_min": "InpBadCluster1RiskMin",
    "bad_cluster1_risk_max": "InpBadCluster1RiskMax",
    "bad_cluster1_confirm_min": "InpBadCluster1ConfirmMin",
    "bad_cluster1_confirm_max": "InpBadCluster1ConfirmMax",
    "bad_cluster1_mult": "InpBadCluster1Mult",
    "bad_cluster1_signal": "InpBadCluster1Signal",
    "bad_cluster2_hours": "InpBadCluster2Hours",
    "bad_cluster2_risk_min": "InpBadCluster2RiskMin",
    "bad_cluster2_risk_max": "InpBadCluster2RiskMax",
    "bad_cluster2_confirm_min": "InpBadCluster2ConfirmMin",
    "bad_cluster2_confirm_max": "InpBadCluster2ConfirmMax",
    "bad_cluster2_mult": "InpBadCluster2Mult",
    "bad_cluster2_signal": "InpBadCluster2Signal",
    "bad_cluster3_hours": "InpBadCluster3Hours",
    "bad_cluster3_risk_min": "InpBadCluster3RiskMin",
    "bad_cluster3_risk_max": "InpBadCluster3RiskMax",
    "bad_cluster3_confirm_min": "InpBadCluster3ConfirmMin",
    "bad_cluster3_confirm_max": "InpBadCluster3ConfirmMax",
    "bad_cluster3_mult": "InpBadCluster3Mult",
    "bad_cluster3_signal": "InpBadCluster3Signal",
    "bad_cluster4_hours": "InpBadCluster4Hours",
    "bad_cluster4_risk_min": "InpBadCluster4RiskMin",
    "bad_cluster4_risk_max": "InpBadCluster4RiskMax",
    "bad_cluster4_confirm_min": "InpBadCluster4ConfirmMin",
    "bad_cluster4_confirm_max": "InpBadCluster4ConfirmMax",
    "bad_cluster4_mult": "InpBadCluster4Mult",
    "bad_cluster4_signal": "InpBadCluster4Signal",
    "bad_cluster5_hours": "InpBadCluster5Hours",
    "bad_cluster5_risk_min": "InpBadCluster5RiskMin",
    "bad_cluster5_risk_max": "InpBadCluster5RiskMax",
    "bad_cluster5_confirm_min": "InpBadCluster5ConfirmMin",
    "bad_cluster5_confirm_max": "InpBadCluster5ConfirmMax",
    "bad_cluster5_mult": "InpBadCluster5Mult",
    "bad_cluster5_signal": "InpBadCluster5Signal",
    "bad_cluster6_hours": "InpBadCluster6Hours",
    "bad_cluster6_risk_min": "InpBadCluster6RiskMin",
    "bad_cluster6_risk_max": "InpBadCluster6RiskMax",
    "bad_cluster6_confirm_min": "InpBadCluster6ConfirmMin",
    "bad_cluster6_confirm_max": "InpBadCluster6ConfirmMax",
    "bad_cluster6_mult": "InpBadCluster6Mult",
    "bad_cluster6_signal": "InpBadCluster6Signal",
    "bad_cluster_filtered_monthly_stop": "InpBadClusterFilteredMonthlyStop",
    "bad_cluster_filtered_stop_min_balance": "InpBadClusterFilteredStopMinBalance",
    "startup_bad_cluster_max_month_start_balance": "InpStartupBadClusterMaxMonthStartBalance",
    "startup_bad_cluster1_hours": "InpStartupBadCluster1Hours",
    "startup_bad_cluster1_risk_min": "InpStartupBadCluster1RiskMin",
    "startup_bad_cluster1_risk_max": "InpStartupBadCluster1RiskMax",
    "startup_bad_cluster1_confirm_min": "InpStartupBadCluster1ConfirmMin",
    "startup_bad_cluster1_confirm_max": "InpStartupBadCluster1ConfirmMax",
    "startup_bad_cluster1_mult": "InpStartupBadCluster1Mult",
    "startup_bad_cluster1_signal": "InpStartupBadCluster1Signal",
    "startup_bad_cluster2_hours": "InpStartupBadCluster2Hours",
    "startup_bad_cluster2_risk_min": "InpStartupBadCluster2RiskMin",
    "startup_bad_cluster2_risk_max": "InpStartupBadCluster2RiskMax",
    "startup_bad_cluster2_confirm_min": "InpStartupBadCluster2ConfirmMin",
    "startup_bad_cluster2_confirm_max": "InpStartupBadCluster2ConfirmMax",
    "startup_bad_cluster2_mult": "InpStartupBadCluster2Mult",
    "startup_bad_cluster2_signal": "InpStartupBadCluster2Signal",
    "startup_bad_cluster3_hours": "InpStartupBadCluster3Hours",
    "startup_bad_cluster3_risk_min": "InpStartupBadCluster3RiskMin",
    "startup_bad_cluster3_risk_max": "InpStartupBadCluster3RiskMax",
    "startup_bad_cluster3_confirm_min": "InpStartupBadCluster3ConfirmMin",
    "startup_bad_cluster3_confirm_max": "InpStartupBadCluster3ConfirmMax",
    "startup_bad_cluster3_mult": "InpStartupBadCluster3Mult",
    "startup_bad_cluster3_signal": "InpStartupBadCluster3Signal",
    "startup_bad_cluster4_hours": "InpStartupBadCluster4Hours",
    "startup_bad_cluster4_risk_min": "InpStartupBadCluster4RiskMin",
    "startup_bad_cluster4_risk_max": "InpStartupBadCluster4RiskMax",
    "startup_bad_cluster4_confirm_min": "InpStartupBadCluster4ConfirmMin",
    "startup_bad_cluster4_confirm_max": "InpStartupBadCluster4ConfirmMax",
    "startup_bad_cluster4_mult": "InpStartupBadCluster4Mult",
    "startup_bad_cluster4_signal": "InpStartupBadCluster4Signal",
    "enable_htf_net_push_filter": "InpEnableHTFNetPushFilter",
    "htf_net_push_tf": "InpHTFNetPushTF",
    "htf_net_push_bars": "InpHTFNetPushBars",
    "htf_net_push_min_atr": "InpHTFNetPushMinATR",
    "htf_net_push_aligned_mult": "InpHTFNetPushAlignedMult",
    "htf_net_push_neutral_mult": "InpHTFNetPushNeutralMult",
    "htf_net_push_counter_mult": "InpHTFNetPushCounterMult",
    "buy_min_strength": "InpBuyMinStrength",
    "sell_min_strength": "InpSellMinStrength",
    "buy_pos_mult": "InpBuyPosMult",
    "sell_pos_mult": "InpSellPosMult",
    "buy_be_r": "InpBuyBE_R",
    "buy_be_lock": "InpBuyBE_Lock",
    "sell_be_r": "InpSellBE_R",
    "sell_be_lock": "InpSellBE_Lock",
    "buy_dtp_trigger_r": "InpBuyDTPTriggerR",
    "buy_dtp_retrace": "InpBuyDTPRetrace",
    "sell_dtp_trigger_r": "InpSellDTPTriggerR",
    "sell_dtp_retrace": "InpSellDTPRetrace",
    "enable_strong_addon": "InpEnableStrongAddOn",
    "strong_addon_trigger_r": "InpStrongAddOnTriggerR",
    "strong_addon_step_r": "InpStrongAddOnStepR",
    "strong_addon_max_count": "InpStrongAddOnMaxCount",
    "strong_addon_lot_mult": "InpStrongAddOnLotMult",
    "strong_addon_risk_mult": "InpStrongAddOnRiskMult",
    "strong_addon_min_spread_ratio": "InpStrongAddOnMinSpreadRatio",
    "close_retry_cooldown_sec": "InpCloseRetryCooldownSec",
    "max_entries_per_ob": "InpMaxEntriesPerOB",
    "ob_reentry_cooldown_min": "InpOBReentryCooldownMin",
    "reentry_pos_mult": "InpReentryPosMult",
    "continuation_pos_mult": "InpContinuationPosMult",
    "filter_cont_age_min_bars": "InpFilterContAgeMinBars",
    "filter_cont_age_max_bars": "InpFilterContAgeMaxBars",
    "filter_cont_non_deep_only": "InpFilterContNonDeepOnly",
    "filter_buy_no_h1_min_pos_mult": "InpFilterBuyNoH1MinPosMult",
    "filter_buy_no_h1_max_pos_mult": "InpFilterBuyNoH1MaxPosMult",
    "filter_buy_no_h1_pos_mult": "InpFilterBuyNoH1PosMult",
    "boost_in_1h_ob": "InpBoostIn1HOB",
    "ds_weight": "InpDSWeight",
    "dt_addon_boost": "InpDTAddonBoost",
    "bar_period_min": "InpBarTF",
    "bars": "InpBars",
    "ob_scan_depth": "InpOBScanDepth",
    "version": "InpVersion",
    "magic_number": "InpMagicNumber",
    "enable_btc_profile": "InpEnableBTCProfile",
    "btc_profile_symbol": "InpBTCProfileSymbol",
    "btc_bounce_pct": "InpBTCBouncePct",
    "btc_timeout_min": "InpBTCTimeoutMin",
    "btc_max_entry_offset_r": "InpBTCMaxEntryOffsetR",
    "btc_bar_period_min": "InpBTCBarTF",
    "btc_enable_liquidity_sweep": "InpBTCEnableLiquiditySweep",
    "btc_liquidity_sweep_only": "InpBTCLiquiditySweepOnly",
    "btc_no_ob_start_hour": "InpBTCNoOBStartHour",
    "btc_no_ob_end_hour": "InpBTCNoOBEndHour",
    "btc_sl_buffer_atr": "InpBTCSLBufferATR",
    "btc_ob_height_tp_mult": "InpBTCOBHeightTPMult",
    "btc_time_exit_bars": "InpBTCTimeExitBars",
    "btc_sweep_lookback_bars": "InpBTCSweepLookbackBars",
    "btc_sweep_max_range_atr": "InpBTCSweepMaxRangeATR",
    "btc_sweep_min_range_spread_mult": "InpBTCSweepMinRangeSpreadMult",
    "btc_sweep_min_penetration_atr": "InpBTCSweepMinPenetrationATR",
    "btc_sweep_min_wick_pct": "InpBTCSweepMinWickPct",
    "btc_sweep_tp_mult": "InpBTCSweepTPMult",
    "btc_breakeven_r": "InpBTCBreakevenR",
    "btc_breakeven_lock_r": "InpBTCBreakevenLockR",
    "btc_dtp_trigger_r": "InpBTCDTPTriggerR",
    "btc_dtp_retrace": "InpBTCDTPRetrace",
    "btc_fixed_tp_r": "InpBTCFixedTPR",
    "btc_risk_percent": "InpBTCRiskPercent",
    "btc_max_pos_mult": "InpBTCMaxPosMult",
    "btc_max_lot_size": "InpBTCMaxLotSize",
    "btc_max_concurrent": "InpBTCMaxConcurrent",
    "btc_min_risk_spread_ratio": "InpBTCMinRiskSpreadRatio",
    "btc_sweep_pos_mult": "InpBTCSweepPosMult",
    "btc_sweep_max_lot_size": "InpBTCSweepMaxLotSize",
    "btc_low_balance_threshold": "InpBTCLowBalanceThreshold",
    "btc_low_balance_pos_mult": "InpBTCLowBalancePosMult",
    "btc_low_balance_max_lot_size": "InpBTCLowBalanceMaxLotSize",
    "btc_entry_depth_pct": "InpBTCEntryDepthPct",
    "btc_entry_depth_filter": "InpBTCEntryDepthFilter",
    "btc_require_double_touch": "InpBTCRequireDoubleTch",
    "btc_max_entries_per_ob": "InpBTCMaxEntriesPerOB",
    "btc_ob_reentry_cooldown_min": "InpBTCOBReentryCooldownMin",
    "btc_cooldown_bars": "InpBTCCooldownBars",
    "btc_continuation_pos_mult": "InpBTCContinuationPosMult",
    "btc_filter_cont_age_min_bars": "InpBTCFilterContAgeMinBars",
    "btc_filter_cont_age_max_bars": "InpBTCFilterContAgeMaxBars",
    "btc_filter_cont_non_deep_only": "InpBTCFilterContNonDeepOnly",
    "btc_boost_in_1h_ob": "InpBTCBoostIn1HOB",
    "btc_late_bounce_sec": "InpBTCLateBounceSec",
    "btc_late_bounce_mult": "InpBTCLateBounceMult",
    "btc_bounce_sweet_min_pct": "InpBTCBounceSweetMinPct",
    "btc_bounce_sweet_max_pct": "InpBTCBounceSweetMaxPct",
    "btc_outside_bounce_sweet_mult": "InpBTCOutsideBounceSweetMult",
    "btc_bad_risk_min": "InpBTCBadRiskMin",
    "btc_bad_risk_max": "InpBTCBadRiskMax",
    "btc_bad_risk_mult": "InpBTCBadRiskMult",
    "btc_large_risk_min": "InpBTCLargeRiskMin",
    "btc_large_risk_mult": "InpBTCLargeRiskMult",
    "btc_no_entry_hours": "InpBTCNoEntryHours",
    "btc_no_buy_hours": "InpBTCNoBuyHours",
    "btc_no_sell_hours": "InpBTCNoSellHours",
    "btc_low_risk_hours": "InpBTCLowRiskHours",
    "btc_low_risk_hour_mult": "InpBTCLowRiskHourMult",
    "btc_high_risk_hours": "InpBTCHighRiskHours",
    "btc_high_risk_hour_mult": "InpBTCHighRiskHourMult",
    "btc_enable_state_filter": "InpBTCEnableStateFilter",
    "btc_trend_lookback": "InpBTCTrendLookback",
    "btc_swing_strength": "InpBTCSwingStrength",
    "btc_range_be_r": "InpBTCRangeBE_R",
    "btc_range_time_exit": "InpBTCRangeTimeExit",
    "btc_trend_be_r": "InpBTCTrendBE_R",
    "btc_trend_be_lock": "InpBTCTrendBE_Lock",
    "btc_trend_dtp_retrace": "InpBTCTrendDTPRetrace",
    "btc_enable_scoring": "InpBTCEnableScoring",
    "btc_min_score": "InpBTCMinScore",
    "btc_proximity_atr": "InpBTCProximityATR",
    "btc_enable_decay_exit": "InpBTCEnableDecayExit",
    "btc_decay_min_r": "InpBTCDecayMinR",
    "btc_decay_bars": "InpBTCDecayBars",
    "btc_mfe_fail_min_r": "InpBTCMFEFailMinR",
    "btc_mfe_fail_exit_r": "InpBTCMFEFailExitR",
    "btc_no_mfe_exit_bars": "InpBTCNoMFEExitBars",
    "btc_no_mfe_min_peak_r": "InpBTCNoMFEMinPeakR",
    "btc_no_mfe_exit_r": "InpBTCNoMFEExitR",
    "btc_enable_htf_net_push_filter": "InpBTCEnableHTFNetPushFilter",
    "btc_htf_net_push_tf": "InpBTCHTFNetPushTF",
    "btc_htf_net_push_bars": "InpBTCHTFNetPushBars",
    "btc_htf_net_push_min_atr": "InpBTCHTFNetPushMinATR",
    "btc_htf_net_push_aligned_mult": "InpBTCHTFNetPushAlignedMult",
    "btc_htf_net_push_neutral_mult": "InpBTCHTFNetPushNeutralMult",
    "btc_htf_net_push_counter_mult": "InpBTCHTFNetPushCounterMult",
    "btc_close_retry_cooldown_sec": "InpBTCCloseRetryCooldownSec",
    "btc_free_run_min_r": "InpBTCFreeRunMinR",
    "btc_shallow_confirm_pos_min": "InpBTCShallowConfirmPosMin",
    "btc_shallow_confirm_pos_mult": "InpBTCShallowConfirmPosMult",
    "btc_dtp_post_partial_lock_r": "InpBTCDTPPostPartialLockR",
    "btc_dtp_post_partial_retrace": "InpBTCDTPPostPartialRetrace",
    "btc_dtp_reset_peak_after_partial": "InpBTCDTPResetPeakAfterPartial",
    "monthly_zone_reset": "InpMonthlyZoneReset",
    "enable_dual_zone_channel": "InpEnableDualZoneChannel",
    "max_ob_age_bars_tf": "InpMaxOBAgeBarsTF",
    "enable_xau_fage_alt_profile": "InpEnableXAUFageAltProfile",
    "xau_fage_alt_profile_symbol": "InpXAUFageAltProfileSymbol",
    "xau_fage_alt_profile_months": "InpXAUFageAltProfileMonths",
    "xau_fage_alt_use_month_filter": "InpXAUFageAltUseMonthFilter",
    "xau_fage_alt_adaptive_start_day": "InpXAUFageAltAdaptiveStartDay",
    "xau_fage_alt_adaptive_max_balance": "InpXAUFageAltAdaptiveMaxBalance",
    "xau_fage_alt_adaptive_min_price": "InpXAUFageAltAdaptiveMinPrice",
    "xau_fage_alt_adaptive_max_price": "InpXAUFageAltAdaptiveMaxPrice",
    "xau_alt_context_filter1_months": "InpXAUAltContextFilter1Months",
    "xau_alt_context_filter1_no_hours": "InpXAUAltContextFilter1NoHours",
    "xau_alt_context_filter1_mult": "InpXAUAltContextFilter1Mult",
    "xau_alt_context_filter2_max_month_start_balance": "InpXAUAltContextFilter2MaxMonthStartBalance",
    "xau_alt_context_filter2_months": "InpXAUAltContextFilter2Months",
    "xau_alt_context_filter2_mult": "InpXAUAltContextFilter2Mult",
    "xau_alt_context_filter2_no_hours": "InpXAUAltContextFilter2NoHours",
    "xau_alt_context_filter3_max_month_start_balance": "InpXAUAltContextFilter3MaxMonthStartBalance",
    "xau_alt_context_filter3_months": "InpXAUAltContextFilter3Months",
    "xau_alt_context_filter3_mult": "InpXAUAltContextFilter3Mult",
    "xau_alt_context_filter3_no_hours": "InpXAUAltContextFilter3NoHours",
    "xau_alt_context_filter4_max_month_start_balance": "InpXAUAltContextFilter4MaxMonthStartBalance",
    "xau_alt_context_filter4_months": "InpXAUAltContextFilter4Months",
    "xau_alt_context_filter4_mult": "InpXAUAltContextFilter4Mult",
    "xau_alt_context_filter4_no_hours": "InpXAUAltContextFilter4NoHours",
    "xau_alt_context_filter5_max_month_start_balance": "InpXAUAltContextFilter5MaxMonthStartBalance",
    "xau_alt_context_filter5_months": "InpXAUAltContextFilter5Months",
    "xau_alt_context_filter5_mult": "InpXAUAltContextFilter5Mult",
    "xau_alt_context_filter5_no_hours": "InpXAUAltContextFilter5NoHours",
    "xau_alt_monthly_profit_target_stop_months": "InpXAUAltMonthlyProfitTargetStopMonths",
    "enable_xau_trend_profile": "InpEnableXAUTrendProfile",
    "xau_trend_profile_symbol": "InpXAUTrendProfileSymbol",
    "xau_trend_trigger_tf": "InpXAUTrendTriggerTF",
    "xau_trend_trigger_bars": "InpXAUTrendTriggerBars",
    "xau_trend_min_abs_net_atr": "InpXAUTrendMinAbsNetATR",
    "xau_trend_range_tf": "InpXAUTrendRangeTF",
    "xau_trend_range_bars": "InpXAUTrendRangeBars",
    "xau_trend_min_range_atr": "InpXAUTrendMinRangeATR",
    "xau_trend_min_range_net_atr": "InpXAUTrendMinRangeNetATR",
    "xau_trend_min_efficiency": "InpXAUTrendMinEfficiency",
    "trend_confirm_enter_min": "InpTrendConfirmEnterMin",
    "trend_confirm_exit_min": "InpTrendConfirmExitMin",
    "xau_trend_monthly_lock_days": "InpXAUTrendMonthlyLockDays",
    "xau_trend_monthly_stop_loss_pct": "InpXAUTrendMonthlyStopLossPct",
    "xau_trend_context_filter1_months": "InpXAUTrendContextFilter1Months",
    "xau_trend_context_filter1_no_hours": "InpXAUTrendContextFilter1NoHours",
    "xau_trend_context_filter1_mult": "InpXAUTrendContextFilter1Mult",
    "xau_trend_bounce_pct": "InpXAUTrendBouncePct",
    "xau_trend_timeout_min": "InpXAUTrendTimeoutMin",
    "xau_trend_max_entry_offset_r": "InpXAUTrendMaxEntryOffsetR",
    "xau_trend_bar_period_min": "InpXAUTrendBarTF",
    "xau_trend_time_exit_bars": "InpXAUTrendTimeExitBars",
    "xau_trend_breakeven_r": "InpXAUTrendBreakevenR",
    "xau_trend_breakeven_lock_r": "InpXAUTrendBreakevenLockR",
    "xau_trend_dtp_trigger_r": "InpXAUTrendDTPTriggerR",
    "xau_trend_dtp_retrace": "InpXAUTrendDTPRetrace",
    "xau_trend_fixed_tp_r": "InpXAUTrendFixedTPR",
    "xau_trend_risk_percent": "InpXAUTrendRiskPercent",
    "xau_trend_max_pos_mult": "InpXAUTrendMaxPosMult",
    "xau_trend_max_lot_size": "InpXAUTrendMaxLotSize",
    "xau_trend_max_concurrent": "InpXAUTrendMaxConcurrent",
    "xau_trend_min_risk_spread_ratio": "InpXAUTrendMinRiskSpreadRatio",
    "xau_trend_entry_depth_pct": "InpXAUTrendEntryDepthPct",
    "xau_trend_entry_depth_filter": "InpXAUTrendEntryDepthFilter",
    "xau_trend_require_double_touch": "InpXAUTrendRequireDoubleTch",
    "xau_trend_max_entries_per_ob": "InpXAUTrendMaxEntriesPerOB",
    "xau_trend_ob_reentry_cooldown_min": "InpXAUTrendOBReentryCooldownMin",
    "xau_trend_cooldown_bars": "InpXAUTrendCooldownBars",
    "xau_trend_filter_cont_age_min_bars": "InpXAUTrendFilterContAgeMinBars",
    "xau_trend_filter_cont_age_max_bars": "InpXAUTrendFilterContAgeMaxBars",
    "xau_trend_filter_cont_non_deep_only": "InpXAUTrendFilterContNonDeepOnly",
    "xau_trend_enable_htf_net_push_filter": "InpXAUTrendEnableHTFNetPushFilter",
    "xau_trend_htf_net_push_tf": "InpXAUTrendHTFNetPushTF",
    "xau_trend_htf_net_push_bars": "InpXAUTrendHTFNetPushBars",
    "xau_trend_htf_net_push_min_atr": "InpXAUTrendHTFNetPushMinATR",
    "xau_trend_htf_net_push_aligned_mult": "InpXAUTrendHTFNetPushAlignedMult",
    "xau_trend_htf_net_push_neutral_mult": "InpXAUTrendHTFNetPushNeutralMult",
    "xau_trend_htf_net_push_counter_mult": "InpXAUTrendHTFNetPushCounterMult",
    "spread_floor": "InpSpreadFloor",
    # v9.8 势位态动
    "trend_lookback": "InpTrendLookback",
    "swing_strength": "InpSwingStrength",
    "enable_state_filter": "InpEnableStateFilter",
    "range_be_r": "InpRangeBE_R",
    "range_time_exit": "InpRangeTimeExit",
    "trend_be_r": "InpTrendBE_R",
    "trend_be_lock": "InpTrendBE_Lock",
    "trend_dtp_retrace": "InpTrendDTPRetrace",
    "enable_scoring": "InpEnableScoring",
    "proximity_filter": "InpProximityFilter",
    "proximity_atr": "InpProximityATR",
    "min_score": "InpMinScore",
    "enable_decay_exit": "InpEnableDecayExit",
    "decay_min_r": "InpDecayMinR",
    "decay_bars": "InpDecayBars",
    "engulf_body_pct": "InpEngulfBodyPct",
    "enable_momentum_regime": "InpEnableMomentumRegime",
    "weak_exit_min_r": "InpWeakExitMinR",
    "weak_body_shrink_pct": "InpWeakBodyShrinkPct",
    "weak_wick_body_ratio": "InpWeakWickBodyRatio",
    "strong_momentum_bars": "InpStrongMomentumBars",
    "strong_min_body_growth": "InpStrongMinBodyGrowth",
    "strong_weak_reverse_body_pct": "InpStrongWeakReverseBodyPct",
    "strong_max_pullback_pct": "InpStrongMaxPullbackPct",
    "strong_dtp_retrace_mult": "InpStrongDTPRetraceMult",
    "fixed_tp_r": "InpFixedTPR",
    "ob_height_tp_mult": "InpOBHeightTPMult",
    "layered_entry_count": "InpLayeredEntryCount",
    "layered_spacing_pct": "InpLayeredSpacingPct",
    "layered_lot_mult": "InpLayeredLotMult",
    "layered_avg_tp_r": "InpLayeredAvgTP_R",
    "micro_entry_count": "InpMicroEntryCount",
    "micro_entry_lot_mult": "InpMicroEntryLotMult",
    "micro_entry_max_lot_size": "InpMicroEntryMaxLotSize",
    # 部分平仓
    "partial_close_r": "InpPartialCloseR",
    "partial_close_pct": "InpPartialClosePct",
    "partial_post_lock_r": "InpPartialPostLockR",
    "partial_only_deep": "InpPartialOnlyDeep",
    # v9.8a EntryEngine状态机
    "enable_entry_engine": "InpEnableEntryEngine",
    "enable_htf_target": "InpEnableHTFTarget",
    "htf_target_tf": "InpHTFTargetTF",
    "htf_target_lookback": "InpHTFTargetLookback",
    "htf_swing_strength": "InpHTFSwingStrength",
    "htf_min_target_r": "InpHTFMinTargetR",
    "htf_max_target_r": "InpHTFMaxTargetR",
    "htf_measured_move_r": "InpHTFMeasuredMoveR",
    "htf_require_aligned": "InpHTFRequireAligned",
    "htf_partial_r": "InpHTFPartialR",
    "htf_partial_pct": "InpHTFPartialPct",
    "htf_skip_dtp": "InpHTFSkipDTP",
    "htf_skip_trail": "InpHTFSkipTrail",
    "htf_dtp_trigger_r": "InpHTFDTPTriggerR",
    "htf_dtp_retrace": "InpHTFDTPRetrace",
    "htf_dtp_post_partial_retrace": "InpHTFDTPPostPartialRetrace",
    "enable_exit_debug": "InpEnableExitDebug",
    "enable_entry_debug": "InpEnableEntryDebug",
    # === WaiTrade3 SMC 扩展参数 ===
    # P0: 市场结构跟踪
    "enable_structure_tracker": "InpEnableStructureTracker",
    "structure_lookback_bars": "InpStructureLookbackBars",
    "structure_pivot_bars": "InpStructurePivotBars",
    "structure_trend_tf": "InpStructureTrendTF",
    "structure_trend_lookback": "InpStructureTrendLookback",
    "structure_min_pivot_strength": "InpStructureMinPivotStrength",
    "structure_require_close": "InpStructureRequireClose",
    "structure_log_bos": "InpStructureLogBOS",
    "structure_block_counter_trend": "InpStructureBlockCounterTrend",
    "structure_block_min_strength": "InpStructureBlockMinStrength",
    "structure_trend_tf": "InpStructureTrendTF",
    "structure_trend_lookback": "InpStructureTrendLookback",
    "structure_trend_stable_bars": "InpStructureTrendStableBars",
    # 趋势自适应出场 (替代二元拦截)
    "enable_trend_adaptive_exit": "InpEnableTrendAdaptiveExit",
    "trend_strength_threshold": "InpTrendStrengthThreshold",
    "counter_trend_sl_mult": "InpCounterTrendSLMult",
    "counter_trend_tp_mode": "InpCounterTrendTPMode",
    # P0: OB多周期堆叠
    "enable_ob_stacking": "InpEnableOBStacking",
    # P0: SL使用H1 ATR
    "sl_use_h1_atr": "InpSLUseH1ATR",
    # P0: 多周期OB加权
    "enable_multi_tf_ob": "InpEnableMultiTFOB",
    "mtf_h4_weight": "InpMTFH4Weight",
    "mtf_h1_weight": "InpMTFH1Weight",
    "mtf_m15_weight": "InpMTFM15Weight",
    "mtf_m5_weight": "InpMTFM5Weight",
    "mtf_m1_weight": "InpMTFM1Weight",
    "mtf_ob_sl_buffer_atr": "InpMTFOBSLBufferATR",
    "mtf_confluence_bonus": "InpMTFConfluenceBonus",
    "mtf_ob_max_age_bars": "InpMTFOBMaxAgeBars",
    "mtf_max_ob_per_tf": "InpMTFMaxOBPerTF",
    "mtf_max_weight": "InpMTFMaxWeight",
    "mtf_block_counter_trend": "InpMTFBlockCounterTrend",
    "edge_bounce_only": "InpEdgeBounceOnly",
    "ob_freshness_filter": "InpOBFreshnessFilter",
    "ob_max_mitigations": "InpOBMaxMitigations",
    "bos_retest_entry": "InpBOSRetestEntry",
    "bos_retest_sl_buffer": "InpBOSRetestSLBuffer",
    "bos_retest_tolerance": "InpBOSRetestTolerance",
    "bos_retest_max_bars": "InpBOSRetestMaxBars",
    "bos_retest_weight": "InpBOSRetestWeight",
    # P1: H4自适应重入控制
    "enable_h4_adaptive": "InpEnableH4Adaptive",
    "h4_trend_max_entries_per_ob": "InpH4TrendMaxEntriesPerOB",
    "h4_trend_reentry_cooldown_min": "InpH4TrendReentryCooldownMin",
    "h4_trend_cooldown_bars": "InpH4TrendCooldownBars",
    "h4_chop_max_entries_per_ob": "InpH4ChopMaxEntriesPerOB",
    "h4_chop_reentry_cooldown_min": "InpH4ChopReentryCooldownMin",
    "h4_chop_cooldown_bars": "InpH4ChopCooldownBars",
    # P0: 流动性池
    "enable_liquidity_pool": "InpEnableLiquidityPool",
    "lp_pool_lookback_bars": "InpLPPoolLookbackBars",
    "lp_swing_high_similarity_pct": "InpLPSwingHighSimilarityPct",
    "lp_min_sweep_distance_points": "InpLPMinSweepDistancePoints",
    "lp_sweep_entry_boost": "InpLPSweepEntryBoost",
    "lp_sweep_boost_only": "InpLPSweepBoostOnly",
    "lp_min_range_atr": "InpLPMinRangeATR",
    "lp_log_detection": "InpLPLogDetection",
    # P1: 折扣/溢价区
    "enable_discount_premium": "InpEnableDiscountPremium",
    "discount_max_ratio": "InpDiscountMaxRatio",
    "premium_min_ratio": "InpPremiumMinRatio",
    "dp_htf_period": "InpDPHTFPeriod",
    "dp_lookback_bars": "InpDPLookbackBars",
    "dp_entry_mult": "InpDPEntryMult",
    # P1: OB评分
    "enable_ob_scoring": "InpEnableOBScoring",
    "ob_score_min_pass": "InpOBScoreMinPass",
    "ob_score_trend_weight": "InpOBScoreTrendWeight",
    "ob_score_displacement_weight": "InpOBScoreDisplacementWeight",
    "ob_score_liquidity_weight": "InpOBScoreLiquidityWeight",
    "ob_score_mitigation_weight": "InpOBScoreMitigationWeight",
    "ob_score_discount_weight": "InpOBScoreDiscountWeight",
    "ob_score_log_low": "InpOBScoreLogLow",
    # P2: 结构轨迹止损
    "enable_structure_trail": "InpEnableStructureTrail",
    "struct_trail_trigger_r": "InpStructTrailTriggerR",
    "struct_trail_buffer_atr": "InpStructTrailBufferATR",
    "struct_trail_lookback": "InpStructTrailLookback",
    "struct_trail_only_dtp_free": "InpStructTrailOnlyDTPFree",
}

# trail_levels 映射: (层级索引, 子key) → INP名称
# 注意: trail1 没有 LockMult
TRAIL_MAP = {
    (0, "trigger_r"): "InpTrail1TriggerR",
    (0, "lock_r"): "InpTrail1LockR",
    (1, "trigger_r"): "InpTrail2TriggerR",
    (1, "lock_r"): "InpTrail2LockR",
    (1, "lock_mult"): "InpTrail2LockMult",
    (2, "trigger_r"): "InpTrail3TriggerR",
    (2, "lock_r"): "InpTrail3LockR",
    (2, "lock_mult"): "InpTrail3LockMult",
}


def format_value(v):
    """将Python值转为.set文件格式"""
    if isinstance(v, bool):
        return "true" if v else "false"
    return str(v)


def strategy_to_set(name: str, cfg: dict) -> str:
    """将单个策略配置转为.set文件内容"""
    lines = []

    # 首行注释: 版本 + 描述
    desc = cfg.get("description", "")
    version = cfg.get("version", name)
    lines.append(f"; {version} — {desc}" if desc else f"; {version}")

    # 平铺字段
    for yaml_key, inp_name in FLAT_MAP.items():
        if yaml_key in cfg:
            lines.append(f"{inp_name}={format_value(cfg[yaml_key])}")

    # trail_levels 数组
    trail_levels = cfg.get("trail_levels", [])
    for idx, level in enumerate(trail_levels):
        if not isinstance(level, dict):
            continue
        for sub_key, val in level.items():
            inp_name = TRAIL_MAP.get((idx, sub_key))
            if inp_name:
                lines.append(f"{inp_name}={format_value(val)}")

    return "\n".join(lines) + "\n"


def load_strategies(yaml_path: Path) -> dict:
    """加载YAML策略文件"""
    if not yaml_path.exists():
        print(f"错误: 找不到配置文件 {yaml_path}", file=sys.stderr)
        sys.exit(1)
    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        print(f"错误: YAML根节点必须是字典", file=sys.stderr)
        sys.exit(1)
    return data


def write_set(content: str, output_path: Path):
    """写入.set文件"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"已生成: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="YAML策略定义 → MT5 .set 文件转换器")
    parser.add_argument("strategy", nargs="?", help="策略名称（YAML中的顶层key）")
    parser.add_argument("--all", action="store_true", help="转换所有策略")
    parser.add_argument("--output", "-o", type=Path, help="输出文件路径（单策略模式）")
    parser.add_argument("--output-dir", type=Path, help="输出目录（--all模式）")
    parser.add_argument("--config", type=Path, help="YAML配置路径(默认 strategies.yaml, --v3 时默认 strategies_v3.yaml)")
    parser.add_argument("--v3", action="store_true", help="生成 WaiTrade3 .set (默认加载 config/strategies_v3.yaml, 输出到 Presets/v3/)")
    parser.add_argument("--base", type=str, help="v3模式: 指定v2基础策略(从strategies.yaml继承参数)")
    args = parser.parse_args()

    if not args.strategy and not args.all:
        parser.error("请指定策略名称或使用 --all")
    if args.strategy and args.all:
        parser.error("--all 不能与策略名称同时使用")

    # --v3 时自动切换默认配置路径
    if args.config is None:
        if args.v3:
            args.config = SCRIPT_DIR.parent / "config" / "strategies_v3.yaml"
        else:
            args.config = DEFAULT_YAML


    strategies = load_strategies(args.config)

    if args.all:
        # 批量模式 — 跳过非策略key
        non_strategy_keys = NON_STRATEGY_KEYS
        output_dir = args.output_dir or (SCRIPT_DIR.parent / "mql5" / "Presets" / ("v3" if args.v3 else ""))
        count = 0
        for name, cfg in strategies.items():
            if name in non_strategy_keys:
                continue
            if not isinstance(cfg, dict):
                continue
            content = strategy_to_set(name, cfg)
            filename = cfg.get("version", name)
            write_set(content, output_dir / f"{filename}.set")
            count += 1
        print(f"完成，共转换 {count} 个策略")
    else:
        # 单策略模式
        name = args.strategy
        if name not in strategies:
            print(f"错误: 策略 '{name}' 不存在。可用: {', '.join(strategies.keys())}", file=sys.stderr)
            sys.exit(1)

        cfg = strategies[name]

        # v3 --base 合并: 先加载v2基础策略参数，再用v3策略覆盖
        if args.v3 and args.base:
            base_strategies = load_strategies(DEFAULT_YAML)
            if args.base not in base_strategies:
                print(f"错误: 基础策略 '{args.base}' 不存在于 {DEFAULT_YAML}", file=sys.stderr)
                sys.exit(1)
            base_cfg = dict(base_strategies[args.base])
            base_cfg.update(cfg)  # v3 覆盖 v2 同名参数
            cfg = base_cfg
            # 版本名: v3策略名_基础策略名
            cfg['version'] = f"{cfg.get('version', name)}_{args.base}"

        content = strategy_to_set(name, cfg)
        if args.output:
            write_set(content, args.output)
        else:
            sys.stdout.write(content)


if __name__ == "__main__":
    main()
